### PR TITLE
Remove Lumin source code 

### PR DESCRIPTION
**Pull request by panwrona**
### Purpose of this Pull Request
We are splitting the magic-script-components into components interface and it's platform-specific implementation. Lumin's platform-specific source files are being moved to the magic-script-components-lumin repository. This repository will only contain the common files (such as components.js), docs, website etc.

### CODE REVIEW

**Comment by grozdanov** [comment]
@panwrona would you please, put some explanation describing what is causing files removal and what would be the new structure (pretty much what is happening and why)? I know we talked about that but I would like to have it here documented and as history.

**Comment by grozdanov** [comment]
@panwrona I see that the branch has been create 3 days ago. Since I updated number of files (many builders) over the weekend, please update the new repository with the latest before merging this branch, so we don't loose those updates!

**Comment by panwrona** [comment]
> @panwrona I see that the branch has been create 3 days ago. Since I updated number of files (many builders) over the weekend, please update the new repository with the latest before merging this branch, so we don't loose those updates!

@grozdanov Hey, I already updated the files in the magic-script-components-lumin with your changes & created pull request. Please check if I didn't miss anything! Also, right now I just copied the files and updated them. Do we want to have history of those files in those two repositories? Right now we will need to cherry-pick the commits from this repo to magic-script-components-lumin and "prepare" them (remove doc/website/etc files if there are any)

Also I've already added the explanation of this pull request in it's description :)

> This is not ready yet.
> This needs to be done before the merge:
> 
> 1. "lumin" backend shall be rebased agains the lates changes in this library.
> 2. "lumin" backend shall be published

@leoz As I written above, I created PR with newest changes in magic-script-components-lumin repository. Also if everything's ok, I will prepare this repository to make it public, then I'll finish this PR and merge it

**Comment by panwrona** [comment]
@leoz @grozdanov here is a link for pull request with newest Lumin's source files update: https://github.com/magic-script/magic-script-components-lumin/pull/1

 I also updated all of the tests for magic-script-components-lumin to make them independent from magic-script-components repository. Locally, all of the tests are passing

**Pull request merged**
