### PR TITLE
Improve/toggle type enum

### PR DESCRIPTION
**Pull request by pleszkiewicz**
Expose `ToggleType` enum.

Thank you for your contribution to MagicScript Project.
Before submitting this PR, please make sure:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved terminology
- [ ] You have added unit tests
- [ ] You have updated documentation

### CODE REVIEW

**Review by kpiascik — APPROVED** [review]
What is the default?

**Comment by pleszkiewicz** [comment]
`default` means Toggle. Ideally if we replace `default` with `toggle` but it would require changes in `magic-script-components-lumin`.

```
export const ToggleType = {
    'default': ui.ToggleType.kDefault,
    'checkbox' : ui.ToggleType.kCheckbox,
    'radio': ui.ToggleType.kRadio
}
```

**Comment by pleszkiewicz** [comment]
Could better if we get rid of `ToggleType` and introduce `<Checkbox />`, `<Radio />` and `<Toggle />` components. But it's not a good time for such change, is it?

**Comment by kpiascik** [comment]
It's actually the perfect time for this.   I'd rather have `<Checkbox/>`, `<Radio/>` and `<Toggle/>` for 3.0.0.
It should be a separate PR though.

**Comment by pleszkiewicz** [comment]
Created ticket for that #325

**Pull request merged**
